image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
      dotnet watch --project dotnetcore.csproj run

vscode:
  extensions:
    - muhammad-sammy.csharp
